spring:
  datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/rest-spring-aws?useTimezone=true&serverTimezone=UTC
      username: root
      password: asdf1231
  jpa:
    open-in-view: false
    hibernate.ddl-auto: none
    show-sql: false